# Generated by Django 4.2.11 on 2024-04-16 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingItem',
            fields=[
                ('task_id', models.CharField(default=uuid.UUID('419a163d-ac34-493c-ad8b-d1d365165e3f'), max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
